/* Advanced Quant Lab — client-side only, derived from each imported CSV. */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id), clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
  const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
  const percentile=(a,p)=>{if(!a.length)return 0;const x=[...a].sort((m,n)=>m-n),i=(x.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return x[l]+(x[h]-x[l])*(i-l);};
  const sd=a=>a.length>1?Math.sqrt(a.reduce((s,x)=>s+(x-mean(a))**2,0)/(a.length-1)):0;
  const fmt=(x,d=1)=>Number.isFinite(x)?x.toFixed(d):'—', pct=(x,d=1)=>Number.isFinite(x)?x.toFixed(d)+'%':'—';
  const cash=x=>(x<0?'−':'')+'$'+Math.abs(x).toLocaleString(undefined,{maximumFractionDigits:0});
  const seeded=seed=>()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};
  const shuffle=(a,r)=>{const x=[...a];for(let i=x.length-1;i;i--){const j=Math.floor(r()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;};
  const table=(heads,rows)=>'<table class="quant-table"><thead><tr>'+heads.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map((x,i)=>'<td>'+(i?'<strong>'+x+'</strong>':x)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
  const insight=(kind,title,text)=>'<div class="quant-insight '+kind+'"><strong>'+title+':</strong> '+text+'</div>';
  function colors(){const c=getComputedStyle(document.getElementById('tabQuant')),v=n=>c.getPropertyValue(n).trim();return {grid:v('--border'),text:v('--text-faint'),green:v('--green'),red:v('--red'),amber:v('--amber'),blue:v('--blue'),bg:v('--surface')};}
  function canvas(id){const el=$(id),w=Math.floor(el.clientWidth),h=Math.floor(el.clientHeight),d=Math.min(2,devicePixelRatio||1);if(w<30||h<30)return null;el.width=w*d;el.height=h*d;const x=el.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);return {el,x,w,h,c:colors(),p:{l:52,r:14,t:15,b:35}};}
  function frame(s,x0,x1,y0,y1,xf=v=>String(Math.round(v)),yf=v=>fmt(v,0)){const {x,w,h,c,p}=s,pw=w-p.l-p.r,ph=h-p.t-p.b,X=v=>p.l+(v-x0)/Math.max(1e-9,x1-x0)*pw,Y=v=>p.t+ph-(v-y0)/Math.max(1e-9,y1-y0)*ph;x.font="11px 'JetBrains Mono',monospace";x.textBaseline='middle';for(let i=0;i<5;i++){const yy=p.t+ph*i/4;x.strokeStyle=c.grid;x.beginPath();x.moveTo(p.l,yy);x.lineTo(w-p.r,yy);x.stroke();x.fillStyle=c.text;x.textAlign='right';x.fillText(yf(y1-(y1-y0)*i/4),p.l-6,yy);const xx=p.l+pw*i/4;x.textAlign='center';x.fillText(xf(x0+(x1-x0)*i/4),xx,h-14);}return {X,Y,pw,ph};}
  function lineChart(id,series,{yPct=false,xLabel='Trade'}={}){const s=canvas(id);if(!s)return;const all=series.flatMap(z=>z.v).filter(Number.isFinite);if(!all.length)return;let lo=Math.min(0,...all),hi=Math.max(0,...all);if(hi===lo)hi=lo+1;const pad=(hi-lo)*.06,f=frame(s,0,Math.max(1,series[0].v.length-1),lo-pad,hi+pad,v=>String(Math.round(v)),v=>yPct?pct(v,0):fmt(v,0));series.forEach(z=>{s.x.strokeStyle=z.color;s.x.lineWidth=z.width||2;s.x.setLineDash(z.dash||[]);s.x.beginPath();z.v.forEach((v,i)=>i?s.x.lineTo(f.X(i),f.Y(v)):s.x.moveTo(f.X(i),f.Y(v)));s.x.stroke();});s.x.setLineDash([]);s.x.fillStyle=s.c.text;s.x.textAlign='center';s.x.fillText(xLabel,s.w/2,s.h-4);}
  function barChart(id,labels,sets,{yPct=false}={}){const s=canvas(id);if(!s)return;const vals=sets.flatMap(z=>z.v),hi=Math.max(1,...vals)*1.08,f=frame(s,0,Math.max(1,labels.length-1),0,hi,i=>labels[Math.round(i)]||'',v=>yPct?pct(v,0):fmt(v,0)),group=(f.pw/labels.length)*.72,bw=group/sets.length;labels.forEach((_,i)=>sets.forEach((z,j)=>{const left=f.X(i)-group/2+j*bw,top=f.Y(z.v[i]);s.x.fillStyle=z.color;s.x.globalAlpha=.78;s.x.fillRect(left,top,Math.max(2,bw-2),f.Y(0)-top);}));s.x.globalAlpha=1;}
  function hist(id,vals,marker){const s=canvas(id);if(!s||!vals.length)return;const lo=Math.min(...vals),hi=Math.max(...vals),n=12,step=(hi-lo)/n||1,b=Array(n).fill(0);vals.forEach(v=>b[clamp(Math.floor((v-lo)/step),0,n-1)]++);const f=frame(s,lo,hi,0,Math.max(...b,1),v=>pct(v,0),v=>fmt(v,0));b.forEach((v,i)=>{s.x.fillStyle=s.c.blue;s.x.globalAlpha=.65;s.x.fillRect(f.X(lo+i*step)+1,f.Y(v),Math.max(2,f.X(lo+(i+1)*step)-f.X(lo+i*step)-2),f.Y(0)-f.Y(v));});s.x.globalAlpha=1;s.x.strokeStyle=s.c.amber;s.x.setLineDash([5,4]);s.x.beginPath();s.x.moveTo(f.X(marker),f.pw?15:15);s.x.lineTo(f.X(marker),s.h-35);s.x.stroke();s.x.setLineDash([]);}
  function tradeDD(vals,start){let e=start,p=start,m=0;for(const v of vals){e+=v;p=Math.max(p,e);m=Math.min(m,(e/p-1)*100);}return m;}
  function streaks(out){let w=0,l=0,mw=0,ml=0;out.forEach(v=>{if(v>0){w++;l=0;mw=Math.max(mw,w);}else if(v<0){l++;w=0;ml=Math.max(ml,l);}});return {mw,ml};}
  function runsZ(out){const a=out.filter(v=>v!==0).map(v=>v>0?1:0),n1=a.reduce((s,v)=>s+v,0),n0=a.length-n1;if(!n1||!n0)return NaN;let runs=1;for(let i=1;i<a.length;i++)if(a[i]!==a[i-1])runs++;const mu=1+2*n1*n0/(n1+n0),vr=2*n1*n0*(2*n1*n0-n1-n0)/((n1+n0)**2*(n1+n0-1));return(runs-mu)/Math.sqrt(vr);}
  function wilson(w,n,z=1.96){if(!n)return[0,0];const p=w/n,d=1+z*z/n,c=(p+z*z/(2*n))/d,h=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return[c-h,c+h];}
  function bootstrap(q,r,reps=600){const vals=q.trades.map(t=>t.net),ex=[],pf=[];for(let k=0;k<reps;k++){const a=Array.from({length:vals.length},()=>vals[Math.floor(r()*vals.length)]),w=a.filter(x=>x>0).reduce((s,x)=>s+x,0),l=Math.abs(a.filter(x=>x<0).reduce((s,x)=>s+x,0));ex.push(mean(a));pf.push(l?w/l:(w?10:0));}return {ex,pf};}
  function simBinary(q,audit,r,riskPct,paths=400,horizon){
    const rules=audit?.rules||PropRules.get(audit?.presetKey),tradesPerDay=Math.max(1,Math.round(q.trades.length/Math.max(1,new Set(q.trades.map(t=>PropRules.key(t.close))).size)));
    const seed=q.trades.reduce((n,t,i)=>(n+Math.round(t.net*100)*(i+1))|0,713);
    const x=PropRules.simulate({rules,payoff:q.kelly.b,winRate:q.kelly.p,risk:riskPct,paths,horizon,tradesPerDay,seed});
    return {...x,risk:riskPct,max:x.max+x.idea,medEnd:percentile(x.ends,.5),medDD:percentile(x.dds,.5),medTime:percentile(x.times,.5),medPassTime:percentile(x.passTimes,.5)};
  }
  function fan(curves,horizon){const p10=[],p50=[],p90=[];for(let i=0;i<=horizon;i++){const a=curves.map(x=>x[Math.min(i,x.length-1)]);p10.push(percentile(a,.1));p50.push(percentile(a,.5));p90.push(percentile(a,.9));}return {p10,p50,p90};}
  function groups(q,key){const m=new Map;q.trades.forEach(t=>{const k=key(t);if(!m.has(k))m.set(k,[]);m.get(k).push(t);});return [...m].map(([name,a])=>({name,n:a.length,net:a.reduce((s,t)=>s+t.net,0),wr:a.filter(t=>t.net>0).length/a.length*100,dd:tradeDD(a.map(t=>t.net),10000)})).sort((a,b)=>Math.abs(b.net)-Math.abs(a.net));}
  function render(q,audit){
    if(!q||!q.trades?.length)return;const seed=q.trades.reduce((s,t,i)=>s+Math.round(t.net*100)*(i+1),0)^q.trades.length,r=seeded(seed),n=q.trades.length,vals=q.trades.map(t=>t.net),wins=q.trades.filter(t=>t.net>0),losses=q.trades.filter(t=>t.net<0),initial=audit?.initial||10000,horizon=clamp(Math.max(n,100),60,250),boot=bootstrap(q,r),ci=wilson(wins.length,n),exCI=[percentile(boot.ex,.025),percentile(boot.ex,.975)],positive=boot.ex.filter(x=>x>0).length/boot.ex.length*100;
    const empiricalRisk=clamp(Math.abs(mean(losses.map(t=>t.net)))/initial*100,.1,3),riskGrid=[];for(let z=.1;z<=3.001;z+=.2)riskGrid.push(simBinary(q,audit,r,+z.toFixed(1),240,horizon));const optimal=riskGrid.reduce((a,b)=>b.pass>a.pass?b:a,riskGrid[0]),actualSim=simBinary(q,audit,r,empiricalRisk,700,horizon),f=fan(actualSim.curves,horizon);
    lineChart('aqlFanChart',[{v:f.p10,color:'#ff5c68',dash:[4,4]},{v:f.p50,color:'#35d07f',width:2.5},{v:f.p90,color:'#57a8ff',dash:[4,4]}]);
    lineChart('aqlRiskChart',[{v:riskGrid.map(x=>x.pass),color:'#35d07f'},{v:riskGrid.map(x=>x.daily+x.max),color:'#ff5c68'}],{yPct:true,xLabel:'Risk steps: 0.1% → 3.0%'});
    const win=clamp(Math.round(Math.sqrt(n)),8,30),rollEx=[],rollWr=[];for(let i=win-1;i<n;i++){const a=q.trades.slice(i-win+1,i+1);rollEx.push(mean(a.map(t=>t.net)));rollWr.push(a.filter(t=>t.net>0).length/a.length*100);}lineChart('aqlRollingChart',[{v:rollEx,color:'#35d07f'},{v:rollWr.map(x=>x/100*sd(vals)),color:'#ffb547',dash:[5,3]}],{xLabel:'Rolling windows'});
    const dds=[];for(let i=0;i<900;i++)dds.push(tradeDD(shuffle(vals,r),initial));const actualDD=tradeDD(vals,initial);hist('aqlShuffleChart',dds,actualDD);
    const afterW=[],afterL=[];for(let i=1;i<n;i++)(q.trades[i-1].net>0?afterW:afterL).push(q.trades[i].net>0?1:0);const condW=mean(afterW)*100,condL=mean(afterL)*100,st=streaks(vals),rz=runsZ(vals);barChart('aqlDependenceChart',['After win','After loss','Overall'],[{v:[condW,condL,q.kelly.p*100],color:'#57a8ff'}],{yPct:true});
    const days=new Map();q.trades.forEach(t=>{const k=t.close.toDateString();days.set(k,(days.get(k)||0)+t.net);});const dayVals=[...days.values()],dailyLimit=initial*(PropRules.get(audit?.presetKey).daily/100);barChart('aqlDailyChart',dayVals.map((_,i)=>String(i+1)),[{v:dayVals.map(x=>Math.max(0,-x)/dailyLimit*100),color:'#ff5c68'}],{yPct:true});
    const stability=rollEx.length<2?'Insufficient':mean(rollEx.slice(-Math.ceil(rollEx.length/3)))>mean(rollEx.slice(0,Math.ceil(rollEx.length/3)))?'Improving':'Weakening';
    $('aqlHeadline').innerHTML='<div class="quant-stat"><div class="quant-stat-label">edge confidence</div><div class="quant-stat-value">'+pct(positive,0)+'</div><div class="quant-stat-sub">bootstrap P(expectancy &gt; 0)</div></div><div class="quant-stat"><div class="quant-stat-label">optimal tested prop risk</div><div class="quant-stat-value">'+pct(optimal.risk,1)+'</div><div class="quant-stat-sub">highest simulated pass rate</div></div><div class="quant-stat"><div class="quant-stat-label">edge regime</div><div class="quant-stat-value">'+stability+'</div><div class="quant-stat-sub">rolling '+win+'-trade window</div></div><div class="quant-stat"><div class="quant-stat-label">sequence luck</div><div class="quant-stat-value">P'+fmt(dds.filter(x=>x<=actualDD).length/dds.length*100,0)+'</div><div class="quant-stat-sub">actual DD among shuffles</div></div>';
    const scenarios=[['Empirical current risk',empiricalRisk],['Full Kelly',q.kelly.full*100],['Half Kelly',q.kelly.half*100],['Quarter Kelly',q.kelly.quarter*100],['⅛ Kelly',q.kelly.full*12.5]].map(([name,risk])=>{const x=simBinary(q,audit,r,clamp(risk,.01,99),350,horizon);return[name,pct(risk,2),pct(x.pass,1),pct(x.daily+x.max,1),fmt(x.medTime,0)];});
    $('aqlSurvival').innerHTML=table(['Scenario','Risk','Pass','Breach','Median trades'],scenarios);
    $('aqlConfidence').innerHTML=table(['Diagnostic','Result','Interpretation'],[['Trades / trading days',n+' / '+days.size,n<30?'Small sample':'Usable history'],['Win-rate 95% interval',pct(ci[0]*100,1)+'–'+pct(ci[1]*100,1),'Wilson interval'],['Expectancy 95% interval',cash(exCI[0])+' to '+cash(exCI[1]),'Trade bootstrap'],['P(expectancy > 0)',pct(positive,1),positive>=95?'Strong historical support':positive>=75?'Uncertain':'Weak'],['Effective day count',days.size,'Days, not positions']]);
    const sorted=[...vals].sort((a,b)=>b-a),stress=k=>{const a=[...vals];sorted.slice(0,k).forEach(v=>a.splice(a.indexOf(v),1));const w=a.filter(x=>x>0).reduce((s,x)=>s+x,0),l=Math.abs(a.filter(x=>x<0).reduce((s,x)=>s+x,0));return {net:a.reduce((s,x)=>s+x,0),pf:l?w/l:Infinity,ex:mean(a)};};
    $('aqlOutliers').innerHTML=table(['Removed','Net','PF','Expectancy'],[['None',cash(q.s.net),Number.isFinite(q.s.pf)?fmt(q.s.pf,2):'∞',cash(q.s.expectancy)],...([1,3,5].filter(k=>k<n).map(k=>{const x=stress(k);return['Best '+k,cash(x.net),Number.isFinite(x.pf)?fmt(x.pf,2):'∞',cash(x.ex)];}))]);
    $('aqlTiming').innerHTML=table(['Outcome','Probability','Typical timing'],[['Reach target',pct(actualSim.pass,1),actualSim.passTimes.length?fmt(actualSim.medPassTime,0)+' trades':'No targets in sample'],['Daily-loss breach',pct(actualSim.daily,1),'Closed-P/L approximation'],['Maximum-loss breach',pct(actualSim.max,1),'Selected total-loss floor / trade-idea cap'],['Unfinished by '+horizon+' trades',pct(actualSim.unfinished,1),'Simulation horizon']]);
    const afterLossLots=[],afterWinLots=[];for(let i=1;i<n;i++){const a=q.trades[i-1].net<0?afterLossLots:afterWinLots;if(q.trades[i].lots>0)a.push(q.trades[i].lots);}const lossUpsize=mean(afterWinLots)?mean(afterLossLots)/mean(afterWinLots):NaN,big=Math.max(...vals.map(Math.abs)),postBig=[];for(let i=1;i<n;i++)if(Math.abs(vals[i-1])>=percentile(vals.map(Math.abs),.8))postBig.push(q.trades[i].lots);
    $('aqlBehavior').innerHTML=table(['Signal','Result','Flag'],[['Size after loss ÷ after win',Number.isFinite(lossUpsize)?fmt(lossUpsize,2)+'×':'—',lossUpsize>1.15?'Possible recovery sizing':'No strong escalation'],['Loser ÷ winner hold time',q.avgWinMinutes?fmt(q.avgLossMinutes/q.avgWinMinutes,2)+'×':'—',q.avgLossMinutes>q.avgWinMinutes*1.5?'Losers held longer':'Balanced'],['Conditional win rate after loss',pct(condL,1),Math.abs(condL-q.kelly.p*100)>10?'Outcome clustering':'Near baseline'],['Runs-test z-score',fmt(rz,2),Math.abs(rz)>1.96?'Non-random sequence warning':'No strong departure']]);
    const sym=groups(q,t=>t.symbol),dir=groups(q,t=>t.direction.toUpperCase());$('aqlExposure').innerHTML=table(['Group','Trades','Win rate','Net','Max DD'],[...sym.slice(0,5),...dir].map(x=>[x.name,x.n,pct(x.wr,1),cash(x.net),pct(x.dd,1)]));
    const exc=q.trades.filter(t=>Number.isFinite(t.maxUSD)&&Number.isFinite(t.minUSD)),mae=exc.map(t=>Math.abs(t.minUSD)),mfe=exc.map(t=>Math.max(0,t.maxUSD)),ew=exc.filter(t=>t.net>0&&t.maxUSD>0),capture=ew.map(t=>t.net/t.maxUSD*100),gave=ew.map(t=>Math.max(0,t.maxUSD-t.net)),turned=exc.filter(t=>t.net<0&&t.maxUSD>0).length;
    $('aqlExcursion').innerHTML=table(['Diagnostic','Result','Coverage'],[['Median MAE',exc.length?cash(percentile(mae,.5)):'—',exc.length+' / '+n],['Median MFE',exc.length?cash(percentile(mfe,.5)):'—',exc.length+' / '+n],['Winner MFE captured',capture.length?pct(percentile(capture,.5),0):'—',capture.length+' winners'],['Median giveback',gave.length?cash(percentile(gave,.5)):'—',gave.length+' winners'],['Positive → losing close',turned,exc.length+' complete paths']]);
    const rules=PropRules.get(audit?.presetKey);const posDays=dayVals.filter(x=>x>0),best=Math.max(0,...posDays),posTotal=posDays.reduce((s,x)=>s+x,0),bestShare=posTotal?best/posTotal*100:0,needBest50=Math.max(0,best*2-posTotal);$('aqlRules').innerHTML=table(['Rule lens','Result','Meaning'],[['Worst closed day',cash(Math.min(0,...dayVals)),pct(Math.abs(Math.min(0,...dayVals))/dailyLimit*100,1)+' of daily limit'],['Best-day share',rules.bestDay?pct(bestShare,1):'Not required',rules.bestDay?(bestShare>50?'Above 50% consistency line':'Within 50% line'):'Selected plan has no best-day rule'],['Profit needed to dilute best day',rules.bestDay?cash(needBest50):'Not required','Additional positive P/L'],['Longest win / loss streak',st.mw+' / '+st.ml,'Observed sequence']]);
    const actions=[];actions.push(positive<80?insight('risk','Edge validity','Bootstrap support for positive expectancy is only '+pct(positive,0)+'. Collect more independent trading days before increasing size.'):insight('good','Edge validity','Positive expectancy survives '+pct(positive,0)+' of trade bootstraps. Continue monitoring out-of-sample results.'));actions.push(optimal.risk<empiricalRisk?insight('warn','Sizing','Historical average loss implies about '+pct(empiricalRisk,2)+' account risk, above the '+pct(optimal.risk,1)+' highest-pass simulation point.'):insight('good','Sizing','Empirical risk is not above the highest-pass tested risk point.'));actions.push(stress(Math.min(3,n-1)).net<=0?insight('warn','Outlier dependence','Removing the best three trades erases total profitability. Treat the edge as concentrated.'):insight('good','Outlier dependence','The history remains profitable without its best three trades.'));if(lossUpsize>1.15)actions.push(insight('risk','Behavior','Position size rises materially after losses; review recovery-sizing or revenge-trading risk.'));if(rules.bestDay&&bestShare>50)actions.push(insight('warn','Consistency','The best day contributes '+pct(bestShare,1)+' of positive daily P/L; approximately '+cash(needBest50)+' more profit would dilute it to 50%.'));$('aqlActions').innerHTML=actions.join('');
    $('aqlFanNote').textContent='At approximately '+pct(empiricalRisk,2)+' risk per trade: median ending index '+fmt(actualSim.medEnd,1)+', median drawdown '+pct(actualSim.medDD,1)+'. Bands use resampled binary outcomes.';
    $('aqlRiskNote').textContent='Green = pass probability; red = combined closed-P/L breach probability. Highest tested pass rate occurs near '+pct(optimal.risk,1)+' risk per trade.';
    $('aqlRollingNote').textContent='Window = '+win+' trades. Expectancy is shown in dollars; win rate is scaled to the P/L axis for shape comparison. Status: '+stability+'.';
    $('aqlShuffleNote').textContent='Actual maximum drawdown '+pct(actualDD,1)+' versus shuffled median '+pct(percentile(dds,.5),1)+'. Same trades, different order.';
    $('aqlDependenceNote').textContent='Win rate after a win '+pct(condW,1)+', after a loss '+pct(condL,1)+'. Runs-test z = '+fmt(rz,2)+'; |z| > 1.96 is a warning, not proof.';
    $('aqlDailyNote').textContent='Bars show each losing day’s closed P/L as a share of the configured daily-loss limit. Floating equity and timezone alignment remain unavailable.';
    $('aqlMethod').textContent='Advanced-lab method: seeded bootstrap and Monte Carlo results are reproducible for the same file. Prop simulations use observed win rate and average payoff, compound a constant risk fraction, approximate day boundaries using historical trades per day, and apply the selected target, daily floor, static or EOD trailing total floor, minimum days, best-day condition, and modeled per-idea cap. They exclude intratrade floating equity, slippage, changing correlations and edge decay. Confidence intervals are descriptive, not guarantees.';
  }
  window.renderAdvancedQuantLab=render;
})();


